# Generated by Django 5.2.8 on 2025-11-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spot_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(default='Spot', max_length=100)),
                ('category', models.CharField(default='Spot', max_length=100)),
                ('description', models.TextField(default='Spot para patinar')),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(default='https://maps.app.goo.gl/MH7LMjYTEEnPKqPy8', max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spot_images/')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.spot')),
            ],
        ),
    ]
